---
- hosts: rust_app_hosts
  become: yes
  tasks:
    - name: copy the binary file
      copy:
        src: target/release/rust-datatable
        dest: /usr/local/bin/rust-datatable
        owner: root
        mode: '0755'

    - name: copy the env-config file
      copy:
        src: app.rust.env
        dest: /etc/app.rust.env
        owner: root
        mode: '0644'

    - synchronize:
        src: templates
        dest: /usr/local/bin/

    - name: copy service template
      template:
        src: rdatatable.service.j2
        dest: /etc/systemd/system/rdatatable.service
        owner: root
        group: root
        mode: '0644'

    - name: enabled and start the service
      service:
        name: rdatatable
        enabled: yes
        state: restarted